[package]
name = "unlockd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
color-eyre = { version = "0.6.2", default-features = false }
duct = "0.13.6"
log = "0.4.17"
zbus = { version = "3.11.1" }
